vo=gpu
gpu-api=opengl     
hwdec=vaapi
hwdec-codecs=all

scale=bilinear
cscale=bilinear
dscale=bilinear

deband=no
interpolation=no
sigmoid-upscaling=no

video-sync=display-resample
vd-lavc-threads=1

